name: Deploy Storybook

on: push

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn install
      - name: Deploy Storybook to Github page
        run: yarn storybook:deploy --ci
        env:
          GH_TOKEN: trussworks:${{ secrets.GITHUB_TOKEN }}
